name: Verify Code

on: 
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y wget build-essential

    - name: Download and Install PCRE
      run: |
        wget https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download
        tar -xzf pcre-8.45.tar.gz
        cd pcre-8.45
        ./configure
        make
        sudo make install

    - name: Download and Install CppCheck
      run: |
        wget -O cppcheck.tar.gz https://github.com/danmar/cppcheck/archive/refs/tags/2.12.1.tar.gz
        tar -xzf cppcheck.tar.gz
        cd cppcheck-2.12.1
        make MATCHCOMPILER=yes HAVE_RULES=yes CFGDIR=cfg
        sudo cp cppcheck /usr/local/bin/
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Roborio Toolchain
      run: ./gradlew installRoborioToolchain

    - name: Compile code and run tests
      run: ./gradlew build

    - name: Spotless Check
      run: ./gradlew spotlessCheck
