name: Verify Code

on: 
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install CppCheck
      run: sudo apt-get install cppcheck

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Roborio Toolchain
      run: ./gradlew installRoborioToolchain

    - name: Compile code and run tests
      run: ./gradlew build

    - name: Spotless Check
      run: ./gradlew spotlessCheck
